#!/bin/bash

pip3 install --upgrade pynvim 
pip3 install pyyaml ueberzug

# yay
git clone https://aur.archlinux.org/yay.git $home/yay
chown hughie:root -R $home/yay
cd yay
makepkg -si

yay -S  \
abook \
bluejeans \
brave-beta-bin \
conky-cairo \
dracula-gtk-theme \
gotop \
mutt-wizard \
nerd-fonts \
pam-gnupg \
python-pynvim \
ranger \
ttf-font-awesome-5 \
twmn-git \
zoom

