#!/bin/bash

home='/home/hughie'
cd $home

pip3 install --upgrade pynvim 
pip3 install pyyaml 

# yay
git clone https://aur.archlinux.org/yay.git $home/yay
chown hughie:root -R $home/yay
cd yay
makepkg -si

yay -S  \
brave-beta-bin \
mutt-wizard \
nerd-fonts \
python-pynvim \
ranger \
ttf-font-awesome-5 \
twmn-git

chown hughie:hughie -R $home
